#!/usr/bin/env bash
#
# update-to-version.sh — re-apply the Drive-sync mod onto a NEW Readest version.
#
# This is the first half of the "patcher" pipeline. Our mod is a set of git
# commits on the `cloud-sync-mod` branch on top of an upstream base. "Updating"
# means replaying those commits (our new files + our small edits) onto a newer
# upstream tag via git's 3-way rebase:
#   - new files apply cleanly, always;
#   - our edits to upstream files apply automatically UNLESS upstream changed the
#     exact lines we touched, in which case git reports the conflicted file(s)
#     for a human to resolve once. This residual is inherent to any fork; we keep
#     it small by keeping our upstream edits tiny and quarantined.
#
# Usage:
#   tooling/update-to-version.sh <upstream-tag-or-commit> [--build]
#
# Safe by construction: it refuses to run on a dirty tree, snapshots the current
# branch to a backup ref first, and never force-anything. On conflict it stops
# and tells you exactly what to fix.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPO_DIR="$WORKSPACE_DIR/readest-src"
MOD_BRANCH="cloud-sync-mod"
UPSTREAM_REMOTE="upstream"

TARGET="${1:-}"
DO_BUILD="${2:-}"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
fail() { printf '\n\033[1;31mUPDATE FAILED: %s\033[0m\n' "$*" >&2; exit 1; }

[ -n "$TARGET" ] || fail "usage: update-to-version.sh <upstream-tag-or-commit> [--build]"
cd "$REPO_DIR" || fail "fork not found at $REPO_DIR"

# --- preflight -------------------------------------------------------------
[ "$(git rev-parse --abbrev-ref HEAD)" = "$MOD_BRANCH" ] \
  || fail "not on $MOD_BRANCH (run: git switch $MOD_BRANCH)"

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  fail "working tree has uncommitted tracked changes. Commit them, or discard
       build-generated noise first (autogenerated permission .toml, Cargo.toml,
       pnpm-lock). Then re-run."
fi

if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
  fail "this is a shallow clone with no upstream history/tags. Run once (heavy):
       git fetch --unshallow --tags $UPSTREAM_REMOTE
       then re-run this script."
fi

# --- fetch + validate target ----------------------------------------------
log "Fetch upstream tags"
git fetch "$UPSTREAM_REMOTE" --tags || fail "git fetch $UPSTREAM_REMOTE failed"

git rev-parse --verify --quiet "${TARGET}^{commit}" >/dev/null \
  || fail "target ref '$TARGET' not found (try a tag like v0.x.y or a commit sha)"

# --- snapshot, then replay our mod onto the target -------------------------
BACKUP="backup/${MOD_BRANCH}-before-$(git rev-parse --short "$TARGET")"
log "Snapshot current branch → $BACKUP"
git branch -f "$BACKUP" "$MOD_BRANCH"

log "Replay mod commits onto $TARGET (git 3-way rebase)"
if git rebase "$TARGET"; then
  log "Clean replay. Update submodules to the new version's pins"
  git submodule update --init --recursive || fail "submodule update failed"
  printf '\n\033[1;32mUpdated %s onto %s. Backup at %s.\033[0m\n' \
    "$MOD_BRANCH" "$TARGET" "$BACKUP"
  printf 'Remember to update the recorded base commit in readest-src/MOD.md.\n'
else
  CONFLICTS="$(git diff --name-only --diff-filter=U || true)"
  printf '\n\033[1;31mCONFLICT — upstream changed lines our mod also touches.\033[0m\n' >&2
  printf 'Files to resolve:\n%s\n\n' "$CONFLICTS" >&2
  printf 'Fix them, then:  git rebase --continue\n' >&2
  printf 'Or back out:     git rebase --abort   (branch is also saved at %s)\n' "$BACKUP" >&2
  exit 1
fi

# --- optional build --------------------------------------------------------
if [ "$DO_BUILD" = "--build" ]; then
  log "Build the updated app"
  exec "$SCRIPT_DIR/build-mod.sh"
fi

printf '\nNext: tooling/build-mod.sh   (or re-run with --build)\n'
